services:
  app:
    image: softvence/yousef_server:latest
    container_name: yousef-server
    platform: linux/amd64
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - yousef-file_data:/app/uploads
    networks:
      - yousef-network

  db:
    image: postgres:16-alpine
    container_name: yousef-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-yousef_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-yousef123Pass}
      - POSTGRES_DB=${POSTGRES_DB:-yousef_db}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - yousef_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-yousef_user} -d ${POSTGRES_DB:-yousef_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - yousef-network

volumes:
  yousef-file_data:
    driver: local
  yousef_data:
    driver: local

networks:
  yousef-network:
    driver: bridge
